# config.yml
player:
  daily: 350.0 # Amount of money a player gets calling /daily
  hourly: 50.0 # Amount of money a player gets every hour while online
  pay_freq: 4 # How many times in the hour the player gets paid
  mcmmo_scale: 0.005 # Amount of money a player gets as an hourly bonus proportional to their MCMMO level

mob_chances:  # Chance of a mob giving money
  never: 0.0
  occasional: 0.35
  half: 0.5
  frequent: 0.75
  always: 1.0

mob_rewards:
  zombie:
    rate: occasional
    amount: 2.0
  skeleton:
    rate: occasional
    amount: 3.5
  creeper:
    rate: frequent
    amount: 8.0
  enderman:
    rate: always
    amount: 15.0
  spider:
    rate: occasional
    amount: 4.0
  blaze:
    rate: half
    amount: 8.0
  ghast:
    rate: always
    amount: 12.0
  phantom:
    rate: frequent
    amount: 5.0
  slime:
    rate: occasional
    amount: 1.0
  witch:
    rate: always
    amount: 9.0
  wither_skeleton:
    rate: half
    amount: 14.0
  zombie_villager:
    rate: frequent
    amount: 2.5
  magma_cube:
    rate: half
    amount: 3.0
  drowned:
    rate: frequent
    amount: 3.0
  husk:
    rate: occasional
    amount: 2.5
  stray:
    rate: frequent
    amount: 3.5
  vindicator:
    rate: always
    amount: 9.75
  evoker:
    rate: always
    amount: 10.5
  pillager:
    rate: frequent
    amount: 4.5
  ravager:
    rate: always
    amount: 13.5
  vex:
    rate: always
    amount: 8.25
  hoglin:
    rate: half
    amount: 8.0
  piglin:
    rate: half
    amount: 6.0
  piglin_brute:
    rate: always
    amount: 7.5
  zombified_piglin:
    rate: half
    amount: 4.0
  shulker:
    rate: always
    amount: 9.0
  guardian:
    rate: always
    amount: 7.5
  elder_guardian:
    rate: always
    amount: 15.0
  endermite:
    rate: half
    amount: 2.0
  silverfish:
    rate: half
    amount: 2.0
  warden:
    rate: always
    amount: 22.5
